# Generated by Django 3.2.4 on 2021-06-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_auto_20210624_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
    ]
