# Generated by Django 3.2.4 on 2021-06-29 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto', '0006_auto_20210629_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='crypto_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
