# Generated by Django 3.2.4 on 2021-06-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_auto_20210621_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cryptocurrencylog',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
