# Generated by Django 3.2.4 on 2021-07-01 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto', '0012_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='favs',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
