# Generated by Django 3.2.4 on 2021-07-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0016_auto_20210711_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
